import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { ReadData } from "../components/readData";
import { Avatar, Box, Button, Card, Flex, Table, Text } from "@radix-ui/themes";
import { config } from "../wagmi";
import { getAccount, writeContract } from "@wagmi/core";
import Score from "../../abi/Score.json";

interface HashResult {
  hash: string;
  fileName: string;
  fileSize: number;
  timestamp: string;
}

const Home: NextPage = () => {
  const [profileData, setProfileData] = useState<any | null>(null);
  const [hashPdf, setHashPdf] = useState<string | null>(null);
  const [role, setRole] = useState<string>("0x01");
  const [rankOfUser, setRankOfUser] = useState<string | null>(null);

  //

  const uploadScore = async () => {
    const wallet = getAccount(config);
    let hashBytes32 = `0x${hashPdf}`;
    if (hashPdf) {
      // Asegurarse de que el hash tenga el prefijo '0x'
      hashBytes32 = `0x${hashPdf.slice(0, 64)}` as `0x${string}`;
    } else {
      // Si no hay hash, usar bytes32 vacío
      hashBytes32 =
        "0x0000000000000000000000000000000000000000000000000000000000000000";
    }
    writeContract(config, {
      abi: Score.abi,
      address: "0x008aD87EC78FDf57Fa3E84649cc7242eCDbDb8FE",
      functionName: "lockData",
      args: [
        wallet.address as `0x${string}`,
        false,
        role,
        hashBytes32,
        profileData.skillsScore,
        profileData.activityScore,
        profileData.identityScore,
      ],
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Trufy</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className={styles.header}>
        <img src="/Logo.png" alt="rainbow" />
        <ConnectButton />
      </header>

      <main className={styles.main}>
        {rankOfUser ? (
          <>
            <Card>
              <Flex gap="2" align="center">
                <Avatar
                  size="5"
                  src={profileData ? profileData.profilePictureUrl : "user.png"}
                  radius="full"
                  fallback="T"
                />
                <Box>
                  <Text as="div" size="4" weight="bold">
                    {profileData.userName}
                  </Text>
                  <Text as="div" size="4" color="gray">
                    {role === "0x01"
                      ? "Developer"
                      : role === "0x02"
                      ? "Designer"
                      : role === "0x03"
                      ? "Community Manager"
                      : "Marketing"}{" "}
                    rank {rankOfUser}
                  </Text>
                </Box>
              </Flex>
            </Card>
            <h2
              style={{
                marginTop: "20px",
                color: "white",
                fontSize: "1rem",
              }}
            >
              With this rank you can multiply your voting power for example:
            </h2>
            <Table.Root variant="surface">
              <Table.Header>
                <Table.Row>
                  <Table.ColumnHeaderCell>DAO</Table.ColumnHeaderCell>
                  <Table.ColumnHeaderCell>
                    Quadratic Voting Multiplier
                  </Table.ColumnHeaderCell>
                </Table.Row>
              </Table.Header>

              <Table.Body>
                <Table.Row>
                  <Table.RowHeaderCell>
                    <img
                      src="/op.png"
                      alt="rainbow"
                      style={{ width: "80px" }}
                    />
                  </Table.RowHeaderCell>
                  <Table.Cell>
                    <b
                      style={{
                        fontSize: "1rem",
                      }}
                    >
                      {role === "0x01"
                        ? 1.5
                        : role === "0x02"
                        ? 1.2
                        : role === "0x03"
                        ? 1.1
                        : 1.0}
                    </b>
                  </Table.Cell>
                </Table.Row>
                <Table.Row>
                  <Table.RowHeaderCell>
                    <img
                      src="/celo.png"
                      alt="rainbow"
                      style={{ width: "80px" }}
                    />
                  </Table.RowHeaderCell>
                  <Table.Cell>
                    <b
                      style={{
                        fontSize: "1rem",
                      }}
                    >
                      {role === "0x01"
                        ? 3.23
                        : role === "0x02"
                        ? 2.1
                        : role === "0x03"
                        ? 1.5
                        : 1.0}
                    </b>
                  </Table.Cell>
                </Table.Row>
                <Table.Row>
                  <Table.RowHeaderCell>
                    <img
                      src="/gitcoin.png"
                      alt="rainbow"
                      style={{ width: "80px" }}
                    />
                  </Table.RowHeaderCell>
                  <Table.Cell>
                    <b
                      style={{
                        fontSize: "1rem",
                      }}
                    >
                      {role === "0x01"
                        ? 1.2
                        : role === "0x02"
                        ? 1.1
                        : role === "0x03"
                        ? 1.05
                        : 1.0}
                    </b>
                  </Table.Cell>
                </Table.Row>
              </Table.Body>
            </Table.Root>
            <Button
              style={{
                marginTop: "20px",
              }}
              size={"4"}
              color="brown"
              onClick={uploadScore}
            >
              Sign
            </Button>
          </>
        ) : (
          <ReadData
            setProfileData={setProfileData}
            profileData={profileData}
            setRole={setRole}
            role={role}
            setHashPdf={setHashPdf}
            hashPdf={hashPdf}
            rankOfUser={rankOfUser}
            setRankOfUser={setRankOfUser}
          />
        )}

        {/*profileData && (
          <div>
            <h2>Profile Data</h2>
            <p>Username: {profileData.userName}</p>
            <p>Profile Picture: {profileData.profilePictureUrl}</p>
            <p>Identity Score: {profileData.identityScore}</p>
            <p>Skills Score: {profileData.skillsScore}</p>
            <p>Activity Score: {profileData.activityScore}</p>
            <p>Main Wallet: {profileData.mainWallet}</p>
          </div>
        )*/}
      </main>

      <footer className={styles.footer}>
        <p>
          Made with ❤️ by <a href="https://jistro.xyz">jistro</a>,{" "}
          <a href="https://x.com/victorxva">victorxva</a> and{" "}
          <a href="https://x.com/ariutokintumi">ariutokintumi</a>
          {" "}for{" "}
          <a href="https://dorahacks.io/hackathon/ftc-2024/buidl">
            Funding the Commons & Earth Commons Hackathon 2024
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Home;
