import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { ReadData } from "../components/readData";
import { config } from "../wagmi";


interface HashResult {
  hash: string;
  fileName: string;
  fileSize: number;
  timestamp: string;
}



const Home: NextPage = () => {
  const [profileData, setProfileData] = useState<any | null>(null);
  const [hashPdf, setHashPdf] = useState<string | null>(null);
  const [role, setRole] = useState<string>("0x01");

  const [hashResult, setHashResult] = useState<HashResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  //0x008aD87EC78FDf57Fa3E84649cc7242eCDbDb8FE
  

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <ReadData
          setProfileData={setProfileData}
          profileData={profileData}
          setRole={setRole}
          role={role}
          setHashPdf={setHashPdf}
          hashPdf={hashPdf}
          setHashResult={setHashResult}
          hashResult={hashResult}
          setIsLoading={setIsLoading}
          isLoading={isLoading}
        />

        {/*profileData && (
          <div>
            <h2>Profile Data</h2>
            <p>Username: {profileData.userName}</p>
            <p>Profile Picture: {profileData.profilePictureUrl}</p>
            <p>Identity Score: {profileData.identityScore}</p>
            <p>Skills Score: {profileData.skillsScore}</p>
            <p>Activity Score: {profileData.activityScore}</p>
            <p>Main Wallet: {profileData.mainWallet}</p>
          </div>
        )*/}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
