import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { ReadData } from "../components/readData";
import { Avatar, Box, Card, Flex, Table, Text } from "@radix-ui/themes";

interface HashResult {
  hash: string;
  fileName: string;
  fileSize: number;
  timestamp: string;
}

const Home: NextPage = () => {
  const [profileData, setProfileData] = useState<any | null>(null);
  const [hashPdf, setHashPdf] = useState<string | null>(null);
  const [role, setRole] = useState<string>("0x01");
  const [rankOfUser, setRankOfUser] = useState<string | null>(null);

  //0x008aD87EC78FDf57Fa3E84649cc7242eCDbDb8FE

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header>
        <ConnectButton />
      </header>

      <main className={styles.main}>
        {rankOfUser ? (
          <>
            <Card>
              <Flex gap="2" align="center">
                <Avatar
                  size="5"
                  src={profileData ? profileData.profilePictureUrl : "user.png"}
                  radius="full"
                  fallback="T"
                />
                <Box>
                  <Text as="div" size="4" weight="bold">
                    {profileData.userName}
                  </Text>
                  <Text as="div" size="4" color="gray">
                    {role === "0x01"
                      ? "Developer"
                      : role === "0x02"
                      ? "Designer"
                      : role === "0x03"
                      ? "Community Manager"
                      : "Marketing"}{" "}
                    rank {rankOfUser}
                  </Text>
                </Box>
              </Flex>
            </Card>
            <h2
              style={{
                marginTop: "20px",
                color: "white",
                fontSize: "1rem",
              }}
            > 
              With this rank you can multiply your voting power for example:
            </h2>
            <Table.Root variant="surface">
              <Table.Header>
                <Table.Row>
                  <Table.ColumnHeaderCell>DAO</Table.ColumnHeaderCell>
                  <Table.ColumnHeaderCell>
                    Quadratic Voting Multiplier
                  </Table.ColumnHeaderCell>
                </Table.Row>
              </Table.Header>

              <Table.Body>
                <Table.Row>
                  <Table.RowHeaderCell>
                    <img
                      src="/op.png"
                      alt="rainbow"
                      style={{ width: "80px" }}
                    />
                  </Table.RowHeaderCell>
                  <Table.Cell>
                    <b
                      style={{
                        fontSize: "1rem",
                      }}
                    >
                      {role === "0x01"
                        ? 1.5
                        : role === "0x02"
                        ? 1.2
                        : role === "0x03"
                        ? 1.1
                        : 1.0}
                    </b>
                  </Table.Cell>
                </Table.Row>
                <Table.Row>
                  <Table.RowHeaderCell>
                    <img
                      src="/celo.png"
                      alt="rainbow"
                      style={{ width: "80px" }}
                    />
                  </Table.RowHeaderCell>
                  <Table.Cell>
                    <b
                      style={{
                        fontSize: "1rem",
                      }}
                    >
                      {role === "0x01"
                        ? 3.23
                        : role === "0x02"
                        ? 2.1
                        : role === "0x03"
                        ? 1.5
                        : 1.0}
                    </b>
                  </Table.Cell>
                </Table.Row>
                <Table.Row>
                  <Table.RowHeaderCell>
                    <img
                      src="/gitcoin.png"
                      alt="rainbow"
                      style={{ width: "80px" }}
                    />
                  </Table.RowHeaderCell>
                  <Table.Cell>
                    <b
                      style={{
                        fontSize: "1rem",
                      }}
                    >
                      {role === "0x01"
                        ? 1.2
                        : role === "0x02"
                        ? 1.1
                        : role === "0x03"
                        ? 1.05
                        : 1.0}
                    </b>
                  </Table.Cell>
                </Table.Row>
              </Table.Body>
            </Table.Root>
          </>
        ) : (
          <ReadData
            setProfileData={setProfileData}
            profileData={profileData}
            setRole={setRole}
            role={role}
            setHashPdf={setHashPdf}
            hashPdf={hashPdf}
            rankOfUser={rankOfUser}
            setRankOfUser={setRankOfUser}
          />
        )}

        {/*profileData && (
          <div>
            <h2>Profile Data</h2>
            <p>Username: {profileData.userName}</p>
            <p>Profile Picture: {profileData.profilePictureUrl}</p>
            <p>Identity Score: {profileData.identityScore}</p>
            <p>Skills Score: {profileData.skillsScore}</p>
            <p>Activity Score: {profileData.activityScore}</p>
            <p>Main Wallet: {profileData.mainWallet}</p>
          </div>
        )*/}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
